### ISSUE TITLE
Feature request: add support for numbers

### ISSUE THREAD

**Issue by titanism** [mscdex/esqlite#3]
Switching to this package from better-sqlite3 would be possible if Number support was added.

For example, queries that implement a counter (and incrementing and decrementing it), or comparing numbers to one another, or sorting by a column that's a number are all too common practices in SQLite and SQL in general.

**Comment by mscdex** [comment]
I'm not really interested in changing how any data types are handled at this point, especially when it comes to numeric values, for the reasons described in the readme. There is nothing stopping you from doing `+value` or `BigInt(value)` (or using a custom class) if you need to convert from string to a numeric type.
